(ns testcases.large-defprotocol)

(defprotocol Foo
  "Exercises https://github.com/jonase/eastwood/issues/191"
  
  (aa [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ab [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ac [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ad [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ae [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (af [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ag [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ah [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ai [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (aj [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ak [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (al [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (am [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (an [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ao [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ap [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (aq [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ar [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (as [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (at [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (au [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (av [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (aw [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ax [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (ay [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl])
  (az [_ aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl aasdl]
    "dfskasfdasfdf adfkj adfskjadfs lkjdaf lkjadf lkadjsf aldkfj aldsfkj adlskfj aldkfja"))
